version: '3'
services:
  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: conferences
      POSTGRES_PASSWORD: conferences
    ports:
      - "5432:5432"
  maildev:
    image: maildev/maildev
    environment:
      MAILDEV_INCOMING_USER: mailuser
      MAILDEV_INCOMING_PASS: mailpassword
    ports:
      - "1080:80"
      - "1025:25"
